name: Integration Tests

on:
  push:
    branches: master
  schedule:
    - cron: '0 2 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Run the tests
        run: ./run.sh
