name: Integration Tests

on:
  push:
    branches: master
  # TODO schedule

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Run the tests
        run: ./run.sh
